name: Deno CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Run tests
        uses: denolib/deno-action@0.20.0
        args: "tests --config tsconfig.json"
